### ISSUE TITLE
No icon in the left panel (Document List)

### ISSUE THREAD

**Issue by gerardp** [abentele/Fraise#12]
Mac Os 10.12.1

![captura de pantalla 2016-11-08 a las 20 25 34](https://cloud.githubusercontent.com/assets/168353/20113870/7fe8209c-a5f2-11e6-8060-16360d9ab8b1.png)

vs

![captura de pantalla 2016-11-08 a las 20 39 35](https://cloud.githubusercontent.com/assets/168353/20114174/8cafc680-a5f3-11e6-994c-b7a4f9848a40.png)

**Comment by abentele** [comment]
confirm bug
