### ISSUE TITLE
Space Character Ignores Hidden Character Color

### ISSUE THREAD

**Issue by rkarolak** [abentele/Fraise#13]
Something I noticed is that if I enable the showing of hidden characters the space symbol doesn't use the color specified for invisible characters in the preferences. All other characters, like the line feed, are using the correct color but the space character is always black.

**Comment by abentele** [comment]
confirm: that's a bug

**Comment by abentele** [comment]
I'm currently investigating on this, but the solution is not trivial. Maybe the current implementation in FRALayoutManager should be replaced with a NSLayoutManagerDelegate implementation.
