### ISSUE TITLE
Window sizes on retina display

### ISSUE THREAD

**Issue by abentele** [abentele/Fraise#16]
from Erich Kuester: "Auf meinem Retina 13" Macbook ist das Preferences-Fenster doppelt so breit wie es sollte. Haengt mit dem Ersatz von userSpaceScaleFactor durch backingScaleFactor zusammen: Der ist naemlich 2.0 und der userSpaceScaleFactor ist immer 1.0 ... Ich habe in die Variable scaleFactor in FRAGradientBackgroundView.m, FRAInterfacePerformer.m und FRAPreferencesController.m auf 1.0 gesetzt und alles ist gut …"

**Comment by abentele** [comment]
wait for Feedback if it works now on retina displays

**Comment by ekuester** [comment]
On my Retina 13" MacBook all is fine now ...

**Comment by abentele** [comment]
so I close this issue
