### ISSUE TITLE
Automatic updates (maybe distribute using the App Store)

### ISSUE THREAD

**Issue by abentele** [abentele/Fraise#2]
automatic updates didn't work for a long time => automatic updates removed (temporary) with release 3.7.4.

If we would distribute using the Mac App Store, we wouldn't need any proprietary update feature. To be clarified if it would comply with the license of Fraise.

Any automatic update feature would require an active maintainer.

Update using Sparkle while distributing the binaries on github:
- https://sparkle-project.org/
- https://gist.github.com/huangyq23/668e6d6fcccf714e802a

**Comment by abentele** [comment]
automatic updates removed (temporary) with release 3.7.4.

**Comment by abentele** [comment]
If we would distribute using the Mac App Store, we wouldn't need any proprietary update feature. To be clarified if it would comply with the license of Fraise.

**Comment by AntoineHus** [comment]
Hello Everybody, 
I would like to help your porject, where can I start ? Is it possible to take care of the sparkle integration in Fraise ? 

Thank you

**Comment by abentele** [comment]
Hi @AntoineHus, 
please look at my roadmap https://github.com/abentele/Fraise/projects/1.
Currently I'm thinking about renaming Fraise and give it a new repository (for more information about my reasons, see #46). I would appreciate if you would help with the sparkle integration (or some of the other issues), but please wait until I have created the new repository. If you like, you may help me finding a new name for Fraise in the meantime (please comment it here: #46).

You also may contact me in private to discuss how to contribute (abentele.github@icloud.com).

Thank you!

**Comment by abentele** [comment]
This fork is discontinued; see notes on https://github.com/abentele/Fraise; new issue is linked, see above.

Please don't comment on this issue any more.
