### ISSUE TITLE
App still looks like it won't run while it does

### ISSUE THREAD

**Issue by mietcls** [abentele/Fraise#21]
In the dock the icon still has the "ban" sign on it (I uninstalled a previous version where this version has been forked, which would not work on OS Sierra).

<img width="95" alt="screen shot 2017-01-02 at 20 56 26" src="https://cloud.githubusercontent.com/assets/1572885/21595526/1c418b88-d12f-11e6-8a69-9d2c02eb1ffb.png">

**Comment by abentele** [comment]
did you try to remove the Fraise icon from the dock, and add it again after installing the new Fraise version? (please try the current release https://github.com/abentele/Fraise/releases/tag/3.7.6).

I assume this would be a bug of macOS, not of Fraise.

**Comment by mietcls** [comment]
That worked. It was a macOS bug. Thank you so much!
