### ISSUE TITLE
German Translation of "Snippet"

### ISSUE THREAD

**Issue by abentele** [abentele/Fraise#24]
The German translation of "Snippet" is currently "Codeschnipsel".
We should better translate it to "Textfragment".

**Comment by ekuester** [comment]
IMHO I would prefer "Textschnipsel" (sounds more friendly to me ;-)

**Comment by abentele** [comment]
Smultron uses "Textfragment". "Textschnipsel" also sounds good. 

I will compare to translations in similar produkts.

**Comment by abentele** [comment]
This fork is discontinued; see notes on https://github.com/abentele/Fraise; new issue is linked, see above.

Please don't comment on this issue any more.
