### ISSUE TITLE
Install command line tool "fraise" doesn't work because of authentication problems

### ISSUE THREAD

**Issue by abentele** [abentele/Fraise#4]
log output:

authopen: couldn't open /usr/bin/fraise: Operation not permitted
2016-10-09 12:05:32.571564 Fraise[86078:1008437] [Layout] Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you.

=> show Authentication Dialog?

**Comment by abentele** [comment]
comment of Erich Kuester (by mail): "Fraise kann ja unter "Hilfe" seine Kommandozeilenversion installieren. Voreinstellung ist /usr/bin und /usr/share. Ab OSX 10.12 ist aber der rootless Modus aktiviert, der Installation in /usr/bin verhindert. Ich schlage vor, hier die Verzeichnisse /usr/local/bin bzw. /usr/local/share zu verwenden, die bei den meisten Anwendern schon im Pfad liegen duerften. Die Aenderungen lassen sich problemlos durchfuehren, man muss nur daran denken, die Localizable.strings auch zu aendern."

**Comment by ekuester** [comment]
The relevant lines (118 and 147) are in FRAAuthentificationController.m in function installCommandLineUtility. Inside the localisation.strings you have only to change /usr/bin for /usr/local/bin and /usr/share for /usr/local/share. On all Unix systems additional by user installed programs are in the /usr/local directory. An alternative could be /opt where you find the X11 system files ( and maybe the MacPorts installation, what I actually do not like).

**Comment by ekuester** [comment]
Again (see my comment above) it is no bug. Culprit is the rootless mode in macOS for directory /usr/bin and /usr/lib ... You can switch it off but this is not advisable.

**Comment by abentele** [comment]
This fork is discontinued; see notes on https://github.com/abentele/Fraise; new issue is linked, see above.

Please don't comment on this issue any more.
