### ISSUE TITLE
Setting Fraise as the Default App is not working in macOS Sierra

### ISSUE THREAD

**Issue by lalarun** [abentele/Fraise#43]
Really appreciate Andreas Bentele for making Fraise usable in Sierra. Awesome job.

Here is an issue I found in macOS Sierra.

Under macOS Sierra, when trying to set Fraise as the default application for files with extension "txt" is not working.
Finder will somehow revert the default application back to TextEdit.

However, setting Fraise as the default for "a single txt file" works correctly.

Steps to reproduce the bug:

Open Finder -> Pick any txt file -> Right click on the file -> Get Info

In the "Open With" section, select "Fraise".

Click "Change All" and in the "Open With" section, the app somehow reverts back to TextEdit.

It is really puzzling why a single file works but "Change All" fails.

Hope this mystery can be resolved in the future.

**Comment by abentele** [comment]
It should already have been fixed. Which version of Fraise did you use? If it's not 3.7.7, please test with the latest release: https://github.com/abentele/Fraise/releases/tag/3.7.7

**Comment by lalarun** [comment]
Dear Andreas:

  YES, it is fixed in 3.7.7.

  Sorry for proposing this redundant issue as I was using the old version 3.7.4.

  You are AWESOME !!

**Comment by abentele** [comment]
Thanks for response!
Your welcome. Please report any further issue - I will fix all major issues.

So I will close this issue.
