### ISSUE TITLE
We should consider to donate or pay for Fraise

### ISSUE THREAD

**Issue by lalarun** [abentele/Fraise#44]
Dear Andreas:

  Really love your FAST response in handling the bug I reported a couple of days ago. This demonstrated your commitment.

  I really love to see Fraise being maintained "continuously" rather than abandoned again in the future. Thus, in my humble opinion, users of Fraise should consider donating or paying for the long term sustainability of Fraise.

  For the past few years, I have seen so many applications to simply stop its development when there is no financial support behind it. Very often, developers initially get excited when users download their apps. However, as time goes by, those initial excitments fritter away and then the application is "abandoned" just like Fraise in the past.

  Considerations for the "financial" support of Fraise are truly critical. Without any arrangement such as donation, I am just afraid that some day Fraise may be abandoned again.

**Comment by abentele** [comment]
Thanks for posting this interesting idea. I read from your lines that you are very happy to see that Fraise again works and is maintained.

In fact there are some costs, e.g. if I wanted to distribute using the Mac App Store. Donation would be helpful to do investments like that. But there are enough free alternatives for distribution and marketing.

Everything else is spare time to invest in a product for which nobody would like to pay - I myself included. I believe in free open source software, and hope to find some contributors who help me to improve it, with or without donations. If I wanted to earn money with it, I would invest more time and money, and distribute it as closed source using the App Store. But it's a project for which I only work in my spare time.

Currently I think there is a very small community which uses Fraise. Before I ported it to macOS Sierra last year, it was a dead project. My main interest is to have a working release for my personal use. I'm very happy to hear that there is a growing community using Fraise - including you. That's what motivates me.

Having written this, in my opinion it's not the time to think about donations. At least, it's not top priority. Next big step is to do some marketing to bring Fraise back to the users who don't know about it.

Thanks again for your post. I would appreciate any further discussion about that.

**Comment by StephenKing** [comment]
@abentele and all contributors: thanks for your work. It is really a time saver to have Fraise available again. I will contact you in private to make a small donation.

Regarding making it accessible to more users: As a frequent user of Homebrew (Cask), I suggest to make it available through that channel. What's your opinion towards making a PR [here](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fraise.rb)? If positive, do you or should I?

**Comment by abentele** [comment]
@StephenKing: many thanks for the donation!

I've created a new issue #45 to address your suggestion.

**Comment by abentele** [comment]
This fork is discontinued; see notes on https://github.com/abentele/Fraise; new issue is linked, see above.

Please don't comment on this issue any more.
