### ISSUE TITLE
Update fraise Homebrew casc

### ISSUE THREAD

**Issue by abentele** [abentele/Fraise#45]
from #44/@StephenKing: "Regarding making it accessible to more users: As a frequent user of Homebrew (Cask), I suggest to make it available through that channel. What's your opinion towards making a PR here? If positive, do you or should I?"

**Comment by StephenKing** [comment]
Here's the file that needs to be updated: https://github.com/caskroom/homebrew-cask/blob/master/Casks/fraise.rb

**Comment by abentele** [comment]
I've created a pull request for cask: https://github.com/caskroom/homebrew-cask/pull/29524

Documented how to do it: https://github.com/abentele/Fraise/wiki/Update-homebrew-cask

The issue may be closed when the pull request is applied (don't know how long it will take).

**Comment by abentele** [comment]
Current status: the cask maintainers rejected my request.
That's a general problem, which I summarized in #46. I will publish "Fraise" with a new name.

**Comment by abentele** [comment]
This fork is discontinued; see notes on https://github.com/abentele/Fraise; new issue is linked, see above.

Please don't comment on this issue any more.
