### ISSUE TITLE
Print: title line and first line overlap

### ISSUE THREAD

**Issue by abentele** [abentele/Fraise#5]

**Comment by ekuester** [comment]
The value for the top margin is too little: If you change in file FRAProject.m at function printInfo line 166 (value 22 to 32 or higher) it looks good. Maybe now the page size dimensions are out of balance: The document has only one page, but now two pages (one empty) is printed. As we say here: Wir sind noch nicht an Schmitz Backes vorbei ;-)

**Comment by abentele** [comment]
Further problems:
- changing the header yes/no setting doesn't update the print preview
- changing the font in the Fraise print settings doesn't work
- changing the margin in the Fraise print settings doesn't work

**Comment by abentele** [comment]
related issues: #20, #19
