### ISSUE TITLE
bug: Issue Assigning Fraise as Default Application to File Types in the Finder

### ISSUE THREAD

**Issue by rkarolak** [abentele/Fraise#6]
I was trying to set a document type to open with Fraise by default, but when I try to do so it instead changes the default application to Apple's TextEdit. Setting the document's default application to other editor applications, such as Textmate or VimR, work fine.

Steps to Reproduce:

Find a document with the file type of what you want to change the default application for. Ex: ~/test.txt

Right click on the document in the Finder.

Expand "Open With:"

Select Fraise from the dropdown menu.

Click "Change All..."

Expected Behavior: The application in the dropdown menu shows "Fraise".

Opening the document from the Finder opens the document (ex. test.txt) in Fraise.

Actual Result: The dropdown menu shows "TextEdit".

Opening the document from the Finder opens the document (ex. test.txt) in TextEdit.

**Comment by rkarolak** [comment]
Tested in macOS Sierra 10.12 (16A323).

**Comment by abentele** [comment]
I confirm, that's a bug. I can reproduce it.
Do you know if it worked with previous versions of Fraise? (Fraise 3.7.3 and earlier)

**Comment by rkarolak** [comment]
I went to try the old version of Fraise, and it's telling me that I:

> can't use this version of "Fraise" with this version of macOS.

If I remember correctly, assigning document types to Fraise worked in OS X 10.11, but I can't say for sure. I can't test that on my Mac.

My parents probably haven't upgraded their Mac Mini to 10.12 yet. They tend to wait a while before installing major updates. If they haven't then I can ask them to try it.
