### ISSUE TITLE
replace project files, file tabs and document list with a folder browser

### ISSUE THREAD

**Issue by abentele** [abentele/Fraise#8]
Neither the file tabs (classes PSMTab*) nor the document list are a pretty feature or look native on the Mac. And, they don't have any feature other than selecting an open file. Moreover the Fraise project feature, which works with proprietary project files, should be completely removed in favor of a file browser with many features, without the need for any project files.

With this feature request, I want to propose to replace these features with a file browser compared to the file tree in Atom text editor. It has many extra features needed to efficiently work with a folder full of source text files (e.g. a Javascript application project).

Comments on this are welcome.

**Comment by abentele** [comment]
related to https://github.com/jfmoy/Fraise/issues/44

**Comment by amrx06** [comment]
you can drag a file to the File Tab and it opens. That's a nice feature i want to keep and I prefer selecting files in file tab than in tabs.
you can add a folder browsing tab but not in replacement of the file tab. I thing the browsing folder tab looks very geek and is intended to people with many files in the same folder, like coders. When I code I use Xcode or pycharm which have these functionalities.

**Comment by abentele** [comment]
@amrx06: I partially agree. We should retain the tabs. But I don't agree a browsing folder would be a geek feature. Look e.g. at Atom editor: it has a very nice file browser with many useful features. Important: it doesn't display any virtual "project" structure like XCode which you have to maintain but simply the structure represented by the file system. 

As a web developer working on a project with a bunch of javascript and html files a lightweight editor with this feature would be my preferred tool. Fraise is already targeted to advanced users like coders (with features like syntax highlighting), and this is one of the features a coder would miss.

**Comment by gerardp** [comment]
If you want to add a folder browser it's ok, but for me the document list it's a very useful feature, please don't remove it.

**Comment by abentele** [comment]
@gerardp: thanks for your comment. For me, the document list and tabs are almost the same feature. The difference is the different rendering vertically vs. horizonally, involved with a bit different behavior, but essentially the same feature. Do you think you could get used to tabs in place of a document list?

I think a good compromise would be a file/folder browser at the left and tabs for opened files at the top of the window, like Atom does.

**Comment by gerardp** [comment]
@abentele 
Thanks for your understanding. In my workflow i use atom and fraise, so having an atom clone is not very useful for me. 
May be you can launch a stable version (3.7.5) with bug fixes and the document list, and another version (3.8.0) with the sidebar and tabs.

Anyway thank you for your work on this project.

**Comment by abentele** [comment]
@gerardp: the plan is not to build an atom clone, but to implement an important missing feature. I only mentioned atom because it would be much more text to describe this feature, and atom already has it.

Regarding the versions: you speak about the roadmap. That's exactly what I do: build a more stable version with many bug fixes and minor features (3.7.5). At the same time talking about new features for the next major release.

**Comment by abentele** [comment]
This fork is discontinued; see notes on https://github.com/abentele/Fraise; new issue is linked, see above.

Please don't comment on this issue any more.
